enable-magisk-update = false
parallel-jobs = 1

[eBay]
version = "latest"
arch = "arm64-v8a"
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ebay-mobile/ebay"

[Music]
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.uptodown.com/android"

[YouTube]
arch = "arm64-v8a"
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.uptodown.com/android"
