name: Build Modules
on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true

  workflow_dispatch:

jobs:
  build:
    name: build
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Update config
        if: ${{ inputs.from_ci }}
        run: |
          if git checkout origin/update build.md; then
            UPDATE_CFG=$(./build.sh config.toml --config-update)
            if [ "$UPDATE_CFG" ]; then
              echo "$UPDATE_CFG" > config.json
            fi
          fi

      - name: Build modules/APKs
        run: if [ -f "config.json" ]; then ./build.sh config.json; else ./build.sh config.toml; fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          NEXT_VER_CODE: 1

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build/

      - name: Get output
        id: set-matrix
        run: echo "matrix=$(ls ./build/ | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  upload:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
        matrix:
            apk: ${{ fromJson(needs.build.outputs.matrix) }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build/
  
      - name: Upload apk to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/${{ matrix.apk }}
          tag: ${{ matrix.apk }}
          overwrite: true

  clean:
    needs: upload
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: build
